Added Go style variable declaration (:= operator)
wren-lang/wren pull request #943
Opened 2021-03-29 04:30 UTC by CrazyInfin8

Added ability to declare variables using the `:=` operator just like in Go

This way, instead of:
```js
var a = "Hello world!"
```
we could shorten it to:
```js
a := "Hello world!"
```

2021-03-29 04:31 UTC, ChayimFriedman2 commented
I don't see any advantage in this.

2021-03-29 04:32 UTC, ChayimFriedman2 requested changes

2021-03-29 04:32 UTC, ChayimFriedman2 commented on src/vm/wren_compiler.c
> +  else if(peek(compiler) == TOKEN_NAME && peekNext(compiler) == TOKEN_COLONEQ)
You missed a space here (after `else if`).

2021-03-29 13:01 UTC, mhermier commented
I see 2 advantages to ':=' operator:
- it allows to chain variable declarations contrary to var
- It can allows to solve the awkward situation we have with `if` implicit var declaration
```javascript
var a = foo()
var b = bar()
if (d := c := b = a) {
  ...
}
```

2021-03-29 21:37 UTC, ChayimFriedman2 commented
> * It can allows to solve the awkward situation we have with `if` implicit var declaration

Not at this form (this is a statement too. In fact, it's a statement in Go too).

2021-03-29 21:38 UTC, ChayimFriedman2 approved these changes

2021-03-29 21:41 UTC, CrazyInfin8 commented
> 
> 
> I see 2 advantages to ':=' operator:
> 
>     * it allows to chain variable declarations contrary to var
> 
>     * It can allows to solve the awkward situation we have with `if` implicit var declaration
> 
> 
> ```js
> var a = foo()
> var b = bar()
> if (d := c := b = a) {
>   ...
> }
> ```

Unfortunately, as @ChayimFriedman2 says, the `:=` operator (or statement I guess) currently behaves exactly as a variable declaration just like how `var` works
that means that these examples still produce syntax errors:
```js
b := a := 5 // error
if(a := true) { // error
    ...
}
System.print(a := 5) // error
```
This is probably just syntactic sugar so users don't have to write `var` all the time

2021-03-30 06:41 UTC, mhermier commented
Yes, but it is a syntax sugar that does not have the constraint of using a keyword:
```javascript
var a = b = 42 // fells more like we are assigning b to 42 and defining a to b
a := b := 42 // You can tell that a and b are new and assigned to 42
```
I don't say it has to be done as this, but it opens a possibility that the other syntax does not have.

2021-03-30 12:46 UTC, PureFox48 commented
I'm against this change.

Although I like and use Go, it's a quirky language and Pascal-style variable declarations were introduced to enable local variable type inference, a problem which Wren simply doesn't have.

When reading code,  it's easy to miss whether you're declaring a new variable or assigning to an existing one as there's only a single character difference.

Note that even in Go you can only use ```:=``` within a function, you have to use ```var``` for top-level variable declarations.

One thing I like about Wren is that there's generally just one way to do things. Variable declarations are fine as they are.

2021-04-08 06:56 UTC, ruby0x1 commented
Along with the other points made above, I don't think this fits Wren and doesn't seem to add much except a bit of noise and inconsistency in the language.

Thanks for the suggestion and PR though!

2021-04-08 06:56 UTC, closed without merging